load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "geometry",
    srcs = [
        "cube.hpp",
        "edLookupTable.hpp",
        "fixedVec.hpp",
        "fixedVecOperations.hpp",
        "grid.hpp",
        "gridSchedual.hpp",
        "molecule.hpp",
        "particle.hpp",
        "particleContainer.hpp",
        "particleContainerChaperone.hpp",
        "particleInteractionHandler.hpp",
        "particleStats.hpp",
        "sphere.hpp",
        "voxel.hpp",
        "voxelInteractionHandler.hpp",
    ],
    visibility = ["//visibility:public"],
)
