cc_binary(
  name = "genTestGraphAndCoords",
  srcs = ["genTestGraphAndCoords.cpp"]
)

cc_binary(
  name = "voxelInteractionTest",
  srcs = ["voxelInteractionTest.cpp"],
  deps = [
    "//include:include"
  ]
)