load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "utils",
    srcs = [
        "calcFuncs.cc",
        "timeKeeper.hpp",
    ],
    hdrs = [
        "calcFuncs.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src:configs",
    ],
)
