load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "configs",
    hdrs = [
        "configs.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/graph",
        "//src/threading",
        "//src/geometry"
    ],
)
