cc_binary(
  name = "lglbreakup",
  srcs = ["lglbreakup.C"],
  deps = [
    "//include:include"
  ]
)

cc_binary(
  name = "lglayout",
  srcs = ["lglayout.C"],
  deps = [
    "//include:include",
    "//include:calcFuncs"
  ]
)

cc_binary(
  name = "lglrebuild",
  srcs = ["lglrebuild.C"],
  deps = [
    "//include:include",
    "//include:calcFuncs"
  ]
)

cc_binary(
  name = "lglfileconvert",
  srcs = ["lglfileconvert.C"],
  deps = [
    "//include:include",
  ]
)